name: Discord Bot

on:
  push:
    branches: ["main"]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Node.js kur
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Paketleri kur
        run: npm install

      - name: Botu çalıştır
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          if [ -z "$DISCORD_TOKEN" ]; then
            echo "TOKEN YOK"
            exit 1
          else
            echo "TOKEN GITHUB'A GELİYOR"
          fi
          node index.js
