- name: Botu çalıştır
  env:
    DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  run: |
    if [ -z "$DISCORD_TOKEN" ]; then
      echo "TOKEN YOK"
      exit 1
    else
      echo "TOKEN GITHUB'A GELİYOR"
    fi
    node index.js
